### ISSUE TITLE
Each scenario has to start with a "green flag clicked"

### ISSUE THREAD

**Issue by MarcSchober** [prokls/scratch-html5-tester#1]
If there is time this issue (or missing feature ;-) ) should be implemented.
Workaround: insert a "when green flag clicked" in the Scratch project and in the corresponding scenario in the feature file.

**Comment by prokls** [comment]
How do you mean?

Expected behavior is that every scenario starts with a "green flag clicked" block in the beginning. I think this is already given in all feature files.

**Comment by MarcSchober** [comment]
You are right, sorry for confusion.
